# library

In [52]:
import pandas as pd
import numpy as np

# load data preproessed_RFM

In [53]:
data = pd.read_csv(r"D:\Sem 4\Rekomendasi Sistem\Tugas\PA\data\Preprocessed_RFM.csv")
data.head()

,TransactionID,CustomerID,TransactionDate,TransactionValue,ProductCategory,PaymentMethod,CustomerGender,CustomerAgeGroup,Region,Recency,Frequency,Monetary
0,TRANS000000,CUST01574,2023-04-09,467907,Sport,Bank Transfer,Female,>50,Surabaya,22,37,86639269
1,TRANS000706,CUST01574,2024-04-22,4908897,Electronics,Bank Transfer,Female,>50,Surabaya,22,37,86639269
2,TRANS000759,CUST01574,2024-05-14,1942602,Beauty,Bank Transfer,Female,>50,Surabaya,22,37,86639269
3,TRANS000863,CUST01574,2024-08-10,462909,Home,Bank Transfer,Female,>50,Surabaya,22,37,86639269
4,TRANS002302,CUST01574,2023-05-20,4019769,Home,Credit Card,Female,>50,Surabaya,22,37,86639269

# Basket Matrix

In [54]:
basket = pd.crosstab(
    data['CustomerID'],
    data['ProductCategory']
)

In [55]:
basket.head()

ProductCategory  Beauty  Electronics  Fashion  Home  Sport
CustomerID
CUST00001             4            7        4     4      3
CUST00002             6            5        5     1      6
CUST00003             7            5        3    10      3
CUST00004             8            8        7     2      8
CUST00005             8           10        2     8      5

# One Hot Encoding

In [56]:
basket = (basket > 0).astype(int)

In [57]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(
    basket,
    min_support=0.05,
    use_colnames=True
)

d:\Sem 4\MLOps\Mg_6\venv\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [58]:
basket.head()

ProductCategory  Beauty  Electronics  Fashion  Home  Sport
CustomerID
CUST00001             1            1        1     1      1
CUST00002             1            1        1     1      1
CUST00003             1            1        1     1      1
CUST00004             1            1        1     1      1
CUST00005             1            1        1     1      1

In [59]:
basket.shape

(2000, 5)

In [60]:
basket.sum()

ProductCategory
Beauty         1988
Electronics    1989
Fashion        1982
Home           1989
Sport          1987
dtype: int64

In [61]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

frequent_itemsets = apriori(
    basket,
    min_support=0.3,
    use_colnames=True
)

frequent_itemsets.sort_values(
    'support',
    ascending=False
).head()

d:\Sem 4\MLOps\Mg_6\venv\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

   support       itemsets
1   0.9945  (Electronics)
3   0.9945         (Home)
0   0.9940       (Beauty)
4   0.9935        (Sport)
2   0.9910      (Fashion)

In [67]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(
    frequent_itemsets,
    metric='support',
    min_threshold=0.01
)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Beauty),(Electronics),0.9940,0.9945,0.9885,0.994467,0.999967,1.0,-0.000033,0.9940,-0.005533,0.9885,-0.006036,0.994217
1,(Electronics),(Beauty),0.9945,0.9940,0.9885,0.993967,0.999967,1.0,-0.000033,0.9945,-0.006033,0.9885,-0.005530,0.994217
2,(Fashion),(Beauty),0.9910,0.9940,0.9850,0.993946,0.999945,1.0,-0.000054,0.9910,-0.006054,0.9850,-0.009082,0.992446
3,(Beauty),(Fashion),0.9940,0.9910,0.9850,0.990946,0.999945,1.0,-0.000054,0.9940,-0.009054,0.9850,-0.006036,0.992446
4,(Beauty),(Home),0.9940,0.9945,0.9885,0.994467,0.999967,1.0,-0.000033,0.9940,-0.005533,0.9885,-0.006036,0.994217

In [63]:
rules = rules[
    (rules['confidence'] >= 0.8) &
    (rules['lift'] >= 1)
]

In [68]:
rules.to_csv(
    'D:\Sem 4\Rekomendasi Sistem\Tugas\PA\data\processed_association_rules.csv',
    index=False
)

<>:2: DeprecationWarning: invalid escape sequence '\S'
<>:2: DeprecationWarning: invalid escape sequence '\S'
C:\Users\ASUS\AppData\Local\Temp\ipykernel_3916\1330432340.py:2: DeprecationWarning: invalid escape sequence '\S'
  'D:\Sem 4\Rekomendasi Sistem\Tugas\PA\data\processed_association_rules.csv',

In [64]:
frequent_itemsets.shape

(31, 2)

In [65]:
frequent_itemsets.head(20)

    support                        itemsets
0    0.9940                        (Beauty)
1    0.9945                   (Electronics)
2    0.9910                       (Fashion)
3    0.9945                          (Home)
4    0.9935                         (Sport)
5    0.9885           (Beauty, Electronics)
6    0.9850               (Fashion, Beauty)
7    0.9885                  (Beauty, Home)
8    0.9875                 (Beauty, Sport)
9    0.9855          (Fashion, Electronics)
10   0.9890             (Electronics, Home)
11   0.9880            (Sport, Electronics)
12   0.9855                 (Fashion, Home)
13   0.9845                (Fashion, Sport)
14   0.9880                   (Sport, Home)
15   0.9795  (Fashion, Beauty, Electronics)
16   0.9830     (Beauty, Electronics, Home)
17   0.9820    (Sport, Beauty, Electronics)
18   0.9795         (Fashion, Beauty, Home)
19   0.9785        (Fashion, Beauty, Sport)

In [66]:
basket.sum()

ProductCategory
Beauty         1988
Electronics    1989
Fashion        1982
Home           1989
Sport          1987
dtype: int64