# library

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# load data hasil preprocessing

In [42]:
data = pd.read_csv(r"D:\Sem 4\Rekomendasi Sistem\Tugas\PA\data\Preprocessed_RFM.csv")
data.head()

,TransactionID,CustomerID,TransactionDate,TransactionValue,ProductCategory,PaymentMethod,CustomerGender,CustomerAgeGroup,Region,Recency,Frequency,Monetary
0,TRANS000000,CUST01574,2023-04-09,467907,Sport,Bank Transfer,Female,>50,Surabaya,22,37,86639269
1,TRANS000706,CUST01574,2024-04-22,4908897,Electronics,Bank Transfer,Female,>50,Surabaya,22,37,86639269
2,TRANS000759,CUST01574,2024-05-14,1942602,Beauty,Bank Transfer,Female,>50,Surabaya,22,37,86639269
3,TRANS000863,CUST01574,2024-08-10,462909,Home,Bank Transfer,Female,>50,Surabaya,22,37,86639269
4,TRANS002302,CUST01574,2023-05-20,4019769,Home,Credit Card,Female,>50,Surabaya,22,37,86639269

# cari kategori terfavorit

In [43]:
favorite = (
    data.groupby(
        ['CustomerID','ProductCategory']
    )
    .size()
    .reset_index(name='count')
)

print("kategori terfavorit setiap pelanggan:")
print(favorite)

kategori terfavorit setiap pelanggan:
     CustomerID ProductCategory  count
0     CUST00001          Beauty      4
1     CUST00001     Electronics      7
2     CUST00001         Fashion      4
3     CUST00001            Home      4
4     CUST00001           Sport      3
...         ...             ...    ...
9930  CUST02000          Beauty      3
9931  CUST02000     Electronics      3
9932  CUST02000         Fashion      4
9933  CUST02000            Home      7
9934  CUST02000           Sport      5

[9935 rows x 3 columns]

# Ambil kategori terbanyak

In [44]:
favorite = favorite.loc[
    favorite.groupby('CustomerID')
    ['count']
    .idxmax()
]

In [45]:
favorite.head()

   CustomerID ProductCategory  count
1   CUST00001     Electronics      7
5   CUST00002          Beauty      6
13  CUST00003            Home     10
15  CUST00004          Beauty      8
21  CUST00005     Electronics     10

# tambahkan gender

In [46]:
gender = (
    data.groupby('CustomerID')
    ['CustomerGender']
    .first()
)

In [47]:
gender = gender.reset_index()
gender.columns = ['CustomerID', 'Gender']

In [48]:
gender.head()

  CustomerID  Gender
0  CUST00001    Male
1  CUST00002  Female
2  CUST00003  Female
3  CUST00004  Female
4  CUST00005    Male

# tambahkan usia

In [49]:
age = (
    data.groupby('CustomerID')
    ['CustomerAgeGroup']
    .first()
)

In [50]:
age = age.reset_index()
age.columns = ['CustomerID', 'AgeGroup']

# tambahkan region

In [51]:
region = (
    data.groupby('CustomerID')
    ['Region']
    .first()
)

In [52]:
region = region.reset_index()
region.columns = ['CustomerID', 'Region']

In [53]:
# ambil Recency
recency = (data.groupby('CustomerID')
    ['Recency']
    .first()
)

In [54]:
recency = recency.reset_index()
recency.columns = ['CustomerID', 'Recency']

In [55]:
# ambil Frequency
frequency = (data.groupby('CustomerID')
    ['Frequency']
    .first()
)

In [56]:
frequency = frequency.reset_index()
frequency.columns = ['CustomerID', 'Frequency']

In [57]:
# ambil Monetary
monetary = (data.groupby('CustomerID')
    ['Monetary']
    .first()
)

In [58]:
monetary = monetary.reset_index()
monetary.columns = ['CustomerID', 'Monetary']

In [ ]:
# favorite_category = favorite[
#     ['CustomerID', 'ProductCategory']
# ].copy()

# favorite_category.columns = [
#     'CustomerID',
#     'FavoriteCategory'
# ]

In [62]:
customer_profile = (
    favorite_category
    .merge(gender, on='CustomerID')
    .merge(age, on='CustomerID')
    .merge(region, on='CustomerID')
    .merge(recency, on='CustomerID')
    .merge(frequency, on='CustomerID')
    .merge(monetary, on='CustomerID')
)

In [63]:
customer_profile.head()

,CustomerID,FavoriteCategory,Gender,AgeGroup,Region,Recency,Frequency,Monetary
0,CUST00001,Electronics,Male,18-25,Surabaya,0,22,63882371
1,CUST00002,Beauty,Female,18-25,Medan,17,23,57227590
2,CUST00003,Home,Female,>50,Medan,21,28,76991379
3,CUST00004,Beauty,Female,18-25,Bandung,9,33,87579881
4,CUST00005,Electronics,Male,18-25,Yogyakarta,20,33,96718054

In [67]:
customer_profile.shape

(2000, 8)

In [66]:
customer_profile['CustomerID'].nunique()

2000

In [70]:
customer_profile.to_csv(
    'D:\Sem 4\Rekomendasi Sistem\Tugas\PA\data\processed_customer_profile.csv',
    index=False
)