# library

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv(r"D:\Sem 4\Rekomendasi Sistem\Tugas\PA\data\UrbanMart_Transactions.csv")
data.head()

,TransactionID,CustomerID,TransactionDate,TransactionValue,ProductCategory,PaymentMethod,CustomerGender,CustomerAgeGroup,Region
0,TRANS000000,CUST01574,2023-04-09,467907,Sport,Bank Transfer,Female,>50,Surabaya
1,TRANS000001,CUST01836,2024-08-05,2713789,Beauty,Credit Card,Female,26-35,Surabaya
2,TRANS000002,CUST01291,2024-04-07,4539248,Fashion,Bank Transfer,Male,18-25,Bandung
3,TRANS000003,CUST00245,2024-06-12,3058426,Home,Bank Transfer,Male,36-50,Jakarta
4,TRANS000004,CUST00163,2023-12-18,3304874,Fashion,Bank Transfer,Female,26-35,Jakarta

# cek informasi data

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TransactionID     50000 non-null  object
 1   CustomerID        50000 non-null  object
 2   TransactionDate   50000 non-null  object
 3   TransactionValue  50000 non-null  int64
 4   ProductCategory   50000 non-null  object
 5   PaymentMethod     50000 non-null  object
 6   CustomerGender    50000 non-null  object
 7   CustomerAgeGroup  50000 non-null  object
 8   Region            50000 non-null  object
dtypes: int64(1), object(8)
memory usage: 3.4+ MB

# cek deskripsi data

In [4]:
data.describe()

       TransactionValue
count      5.000000e+04
mean       2.534081e+06
std        1.429538e+06
min        5.006000e+04
25%        1.304192e+06
50%        2.537391e+06
75%        3.768265e+06
max        4.999929e+06

# cek missing value

In [5]:
data.isnull().sum()

TransactionID       0
CustomerID          0
TransactionDate     0
TransactionValue    0
ProductCategory     0
PaymentMethod       0
CustomerGender      0
CustomerAgeGroup    0
Region              0
dtype: int64

# cek duplikasi data

In [6]:
dup_data = data.duplicated().sum()
print(f"Jumlah data duplikat: {dup_data}")

Jumlah data duplikat: 0

# cek distribusi kategori

In [7]:
data['ProductCategory'].value_counts()

ProductCategory
Beauty         10119
Fashion         9982
Home            9973
Electronics     9971
Sport           9955
Name: count, dtype: int64

# cek distribusi gender

In [8]:
data['CustomerGender'].value_counts()

CustomerGender
Female    27772
Male      22228
Name: count, dtype: int64

# cek distribusi kelompok umur

In [11]:
pd.crosstab(
    data['CustomerGender'],
    data['CustomerAgeGroup'],
    normalize='index'
) * 100

CustomerAgeGroup      18-25      26-35      36-50       >50
CustomerGender
Female            30.311105  39.716261  20.563877  9.408757
Male              30.686522  40.444484  19.821846  9.047148

In [12]:
pd.crosstab(
    data['CustomerGender'],
    data['CustomerAgeGroup']
)

CustomerAgeGroup  18-25  26-35  36-50   >50
CustomerGender
Female             8418  11030   5711  2613
Male               6821   8990   4406  2011

# cek region

In [13]:
data['Region'].value_counts()

Region
Surabaya      9094
Yogyakarta    8624
Medan         8378
Denpasar      8269
Jakarta       7914
Bandung       7721
Name: count, dtype: int64