# library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# load data

In [2]:
data = pd.read_csv(r"D:\Sem 4\Rekomendasi Sistem\Tugas\PA\data\UrbanMart_Transactions.csv")
data.head()

,TransactionID,CustomerID,TransactionDate,TransactionValue,ProductCategory,PaymentMethod,CustomerGender,CustomerAgeGroup,Region
0,TRANS000000,CUST01574,2023-04-09,467907,Sport,Bank Transfer,Female,>50,Surabaya
1,TRANS000001,CUST01836,2024-08-05,2713789,Beauty,Credit Card,Female,26-35,Surabaya
2,TRANS000002,CUST01291,2024-04-07,4539248,Fashion,Bank Transfer,Male,18-25,Bandung
3,TRANS000003,CUST00245,2024-06-12,3058426,Home,Bank Transfer,Male,36-50,Jakarta
4,TRANS000004,CUST00163,2023-12-18,3304874,Fashion,Bank Transfer,Female,26-35,Jakarta

# ubah date --> datetime

In [4]:
data['TransactionDate'] = pd.to_datetime(data['TransactionDate'])

# feature engineer

In [ ]:
# Recency Calculation   
today = data['TransactionDate'].max()

recency = (
    today -
    data.groupby('CustomerID')
    ['TransactionDate']
    .max()
).dt.days

In [8]:
# Frequency Calculation
frequency = (
    data.groupby('CustomerID')
    .size()
)

In [10]:
# Monetary Calculation
monetary = (
    data.groupby('CustomerID')
    ['TransactionValue']
    .sum()
)

In [11]:
# gabungkan RFM ke dalam satu DataFrame
rfm = pd.concat(
    [recency, frequency, monetary],
    axis=1
)

rfm.columns = [
    'Recency',
    'Frequency',
    'Monetary'
]

In [13]:
# gabungkan RFM ke dataset asli
data = data.merge(rfm, left_on='CustomerID', right_index=True)
data.head()

,TransactionID,CustomerID,TransactionDate,TransactionValue,ProductCategory,PaymentMethod,CustomerGender,CustomerAgeGroup,Region,Recency,Frequency,Monetary
0,TRANS000000,CUST01574,2023-04-09,467907,Sport,Bank Transfer,Female,>50,Surabaya,22,37,86639269
706,TRANS000706,CUST01574,2024-04-22,4908897,Electronics,Bank Transfer,Female,>50,Surabaya,22,37,86639269
759,TRANS000759,CUST01574,2024-05-14,1942602,Beauty,Bank Transfer,Female,>50,Surabaya,22,37,86639269
863,TRANS000863,CUST01574,2024-08-10,462909,Home,Bank Transfer,Female,>50,Surabaya,22,37,86639269
2302,TRANS002302,CUST01574,2023-05-20,4019769,Home,Credit Card,Female,>50,Surabaya,22,37,86639269

In [14]:
# simppan dataset yang sudah diproses
data.to_csv(r"D:\Sem 4\Rekomendasi Sistem\Tugas\PA\data\Preprocessed_RFM.csv", index=False)